name = "wallet-api"
main = "worker.js"
compatibility_date = "2026-01-01"

[vars]
# Set this in your Cloudflare dashboard or via wrangler secret:
# wrangler secret put ANKR_API_KEY
ANKR_API_KEY = "72b95ebaabd6c30f74d8779165743207240de8907789c44fddf6ede65115ad8b"

[[kv_namespaces]]
binding = "CHART_CACHE"
id = "dace18326d4d402bbe806a3460056ac4"

[[routes]]
pattern = "api.rivarawallet.xyz"
custom_domain = true

# Cron trigger to refresh prices every 5 minutes
[triggers]
crons = ["*/5 * * * *"]
